### PR TITLE
fix: re-export a default export from a file as the default export

### LINKED ISSUE #182: `export ... from` does not work as expected with a default export
Hi there! Thanks for creating and maintaining this awesome package!

---

### Description

When re-exporting the default export from another file, `dts-bundle-generator` does not `export default` the value.

See a minimal repro [here](https://github.com/gamemaker1/test/tree/dts-bundle-generator).

### Input Code

```ts
// /source/index.ts
// Export away!

// Works if the following is used instead:
// import sayHello from './lib.js'
// export default sayHello

export { default } from './lib.js'
```

```ts
// /source/lib.ts
// Define all library functions

const sayHello = (name: string) => {
	console.log(`'ello there, ${name}!`)
}

export default sayHello
```

### Expected output

```ts
// Generated by dts-bundle-generator v6.2.0

declare const sayHello: (name: string) => void;
export default sayHello; // <== This line should be there

export {};
```

### Actual output

```ts
// Generated by dts-bundle-generator v6.2.0

declare const sayHello: (name: string) => void;

export {};
```

---

I'd be happy to submit a PR to fix this :)

### PR DESCRIPTION
**Pull request by gamemaker1**
### Description

This PR fixes a bug where dts-bundle-generator does not `export default` an expression when re-exporting the default export from another file.

### Related Issues

Fixes #182

### CODE REVIEW

File: src/bundle-generator.ts [hunk 1]
```diff
@@ -198,6 +198,9 @@ export function generateDtsBundle(entries: readonly EntryPointConfig[], options:
 			shouldDeclareExternalModuleBeInlined: () => Boolean(outputOptions.inlineDeclareExternals),
 			getModuleInfo: (fileName: string) => getModuleInfo(fileName, criteria),
 			resolveIdentifier: (identifier: ts.Identifier) => resolveIdentifier(typeChecker, identifier),
+			// @ts-expect-error There is actually a `symbol` property at runtime?!
+			getDefaultExportForSourceFile: (sourceFile: ts.SourceFile) => getExportsForSourceFile(typeChecker, sourceFile.symbol)
+				.filter((exportedExpression) => exportedExpression.exportedName === 'default')[0],
```
Comment (gamemaker1) [inline src/bundle-generator.ts:203]: I think it's unlikely that this will be `undefined`, but I'll add a check anyways

**Comment by gamemaker1** [comment]
[This](https://github.com/timocov/dts-bundle-generator/tree/master/tests%2Fe2e%2Ftest-cases%2Fdefault-export-of-default-export) test also fails, but it is extremely similar to the test case for the bug.

File: src/bundle-generator.ts [hunk 2]
```diff
@@ -447,8 +451,9 @@ function updateResultForRootSourceFile(params: UpdateParams, result: CollectingR
 			for (const exportItem of statement.exportClause.elements) {
 				if (exportItem.name.getText() === 'default' && exportItem.propertyName === undefined) {
 					// export { default }
-					// return export { /get name of exportItem.name's symbol node/ as default };
-					// it seems unnecessary?
+					// return export { /get default export of source file/ as default };
+					const defaultExport = params.getDefaultExportForSourceFile(statement.getSourceFile());
```
Comment (timocov) [inline src/bundle-generator.ts:455]: Hm, have you tried to use `params.resolveIdentifier` for this? It looks like it does quite similar what you need here (it is used in this function to retrieve the same kind of value btw)

**Comment by timocov** [comment]
> but it is extremely similar to the test case for the bug.

It is, yes, but it seems that a generated code right now is incorrect:

```diff
export default class MyClass {
}
       
export {
	MyClass as default,
};

export {};
```

as you can see, there are 2 exports with the same name `default` and [the compiler will raise an error](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBAE2AMwIYFcA28DGnUDOBcAsgJ4DC+RcA3gFAC+9crbc9oksd9AkOSqFihRCgzYANEwDc9TuGjxajGUA) in this case, so we need to fix this as well.

I'd say that for default exports we need to change a behaviour a bit - instead of having `export default` in places where it was originally, we can leave nodes unexported in-place and then use the new behaviour to export them. Thus, for this test case I'd say we need to receive the next output:

```ts
declare class MyClass {
}

export {
	MyClass as default,
};

export {};
```

But here we need to handle a case when a default export doesn't have a name. In this case it should be exported as is, i.e. with `export default`:

<details>
<summary>Input</summary>

**class.ts**:

```ts
export default class {}
```

**input.ts**:
```ts
export { default } from './class';
```
</details>

<details>
<summary>Output</summary>

```ts
export default class {
}

export {};
```
</details>

**Comment by timocov** [comment]
Also, another interesting test case would be re-export default export from importable package - you can add the following line to https://github.com/timocov/dts-bundle-generator/blob/master/tests/e2e/test-cases/re-export-from-importable-module/input.ts:

```ts
export { default } from 'package-with-default-export';
```

And expected output for this should be the following in `output.d.ts`:

```ts
export { default } from "package-with-default-export";
```

**Comment by timocov** [comment]
And probably the last test case I found for this might be the following:

**lib.ts**:

```ts
export const sayHello = (name: string) => {
	console.log(`Hello there, ${name}!`)
}

export default sayHello;
```

**input.ts**:

```ts
export { default } from './lib';
export { sayHello } from './lib';
```

**output.d.ts**:

```ts
export declare const sayHello: (name: string) => void;

export {
	sayHello as default,
};

export {};
```

**Comment by timocov** [comment]
Based on that I'd say:

- if a node (class, function, etc) is declared in root source file and it is exported via `export default`, then it should have `export default` in this node's text
- if a node is declared not in root source file but exported via `export default` then it should have `export default` in its text only if it doesn't have a name (because otherwise it won't work)
- otherwise we should 1) strip both `export` and `default` keywords from a content for this node 2) add `{ name as default }` for such node

Another FYI: it seems that if a named node doesn't have `name` ([here](https://github.com/timocov/dts-bundle-generator/blob/520b76ecc46cc1ab0e1468848cdc76b4fe4e297e/src/bundle-generator.ts#L768) or [here](https://github.com/timocov/dts-bundle-generator/blob/520b76ecc46cc1ab0e1468848cdc76b4fe4e297e/src/helpers/typescript.ts#L265)) and this node is exported via `export default`, we should use `DefaultKeyword` modifier from this node to get a symbol, so you can create a helper something like this:

```ts
export function getStatementNameNode(statement: ts.Node): ts.NamedDeclaration['name'] | ts.DefaultKeyword {
	const statementName = (statement as unknown as ts.NamedDeclaration).name;
	if (statementName === undefined) {
		const defaultModifier = statement.modifiers?.find((mod: ts.Modifier) => mod.kind === ts.SyntaxKind.DefaultKeyword);
		if (defaultModifier !== undefined) {
			return defaultModifier as ts.DefaultKeyword;
		}
	}

	return statementName;
}
```

and use it instead of `(node as unknown as ts.NamedDeclaration).name` in cases above.

File: src/bundle-generator.ts (hunk 2 above)
Comment (gamemaker1) [reply src/bundle-generator.ts:455]: That worked, thanks! Should have noticed it when I was poking around 🤦🏾

**Comment by gamemaker1** [comment]
> And probably the last test case I found for this might be the following...

https://github.com/timocov/dts-bundle-generator/pull/183#issuecomment-1004267667

I added this and it works!

**Comment by gamemaker1** [comment]
Working on [this](https://github.com/timocov/dts-bundle-generator/pull/183#issuecomment-1004266341) now

**Comment by gamemaker1** [comment]
Yay I got https://github.com/timocov/dts-bundle-generator/pull/183#issuecomment-1004266341 working (i.e., we don't touch `export { default }`s from external node modules anymore)

Will work on [this](https://github.com/timocov/dts-bundle-generator/pull/183#issuecomment-1004273260) now.

File: src/bundle-generator.ts [hunk 3]
```diff
@@ -447,8 +447,13 @@ function updateResultForRootSourceFile(params: UpdateParams, result: CollectingR
 			for (const exportItem of statement.exportClause.elements) {
 				if (exportItem.name.getText() === 'default' && exportItem.propertyName === undefined) {
 					// export { default }
-					// return export { /get name of exportItem.name's symbol node/ as default };
-					// it seems unnecessary?
+					// return export { /get default export of source file/ as default };
+					// Leave `export { default } from 'external-package'` untouched
+					if (!isDeclarationFromExternalModule(params.resolveIdentifier(exportItem.name)!.getSourceFile())) {
```
Comment (timocov) [inline src/bundle-generator.ts:452]: I think this could be fixed easier by putting `continue` to [this if statement](https://github.com/timocov/dts-bundle-generator/pull/183/files#diff-5554c0b3649d68de687551481713522cf40d31aa531ea9fb666d71a8ba7afe71R441-R443) (right before this loop) - here we already check that `isReExportFromImportable` and add a statement to result array so it seems that we can skip the later processing there.

Comment (gamemaker1) [reply src/bundle-generator.ts:452]: But I need to leave only `export {default}`s untouched, so the if statement needs to be inside the loop right?

**Comment by gamemaker1** [comment]
Hi @timocov,

I need some help with the following:

> otherwise we should 1) strip both export and default keywords from a content for this node 2) add { name as default } for such node

`statement.modifiers` is a readonly field - and even if I temporarily suppress that error, removing the `export` and `default` modifiers means that the node is not prefixed with `declare` in the `.d.ts` file.

I have pushed the code I have tried out so far - let me know if I'm going in the right direction.

Thanks :)

**Comment by timocov** [comment]
[This function](https://github.com/timocov/dts-bundle-generator/blob/520b76ecc46cc1ab0e1468848cdc76b4fe4e297e/src/bundle-generator.ts#L423-L485) processes the root source, i.e. a source file you provide as an entry point. [In this code](https://github.com/timocov/dts-bundle-generator/blob/520b76ecc46cc1ab0e1468848cdc76b4fe4e297e/src/bundle-generator.ts#L436-L443) we're going through all statements in this root file and check whether a statement is `export =` or `export {} from ''`.
If it is `export =` then we should add this statement to the result as is without any modification.
If it is `export {} from` statement _and_ the package where we have re-export from is importable (i.e. we must not inline it and should use import/export statements to handle it), then we should leave this statement as is as well.
But it seems that accidentally I forget to add `continue` at the end of this `if` statement. So if we add a statement to the result list of statement we don't need to processed with this statement any more.

> The statement.modifiers field is readonly, so I cannot modify it manually.

Yep. To apply some modifications to the result output the tool has a few helpers, which are provided to generate output function.

For example, [needStripDefaultKeywordForStatement](https://github.com/timocov/dts-bundle-generator/blob/520b76ecc46cc1ab0e1468848cdc76b4fe4e297e/src/bundle-generator.ts#L259-L268) allows you to tell whether a `default` keyword should be stripped from the output of a node. So here you can just returned true or false and the tool will handle for you the rest.

Also, there is another helper [shouldStatementHasExportKeyword](https://github.com/timocov/dts-bundle-generator/blob/520b76ecc46cc1ab0e1468848cdc76b4fe4e297e/src/bundle-generator.ts#L270-L307), which is used to detect whether a node/statement should have an `export` keyword at the beginning of the node.

As you can see, in both functions ([here](https://github.com/timocov/dts-bundle-generator/blob/520b76ecc46cc1ab0e1468848cdc76b4fe4e297e/src/bundle-generator.ts#L267) and [here](https://github.com/timocov/dts-bundle-generator/blob/520b76ecc46cc1ab0e1468848cdc76b4fe4e297e/src/bundle-generator.ts#L284-L285)) we're dealing with default export as a special case.

You can play with these 2 functions by returning different values and see how the result is affected. But I believe that the final result in both functions should be something like I described in https://github.com/timocov/dts-bundle-generator/pull/183#issuecomment-1004273260.

Let me know if I need to elaborate anything else.

**Comment by gamemaker1** [comment]
Thanks a lot for the detailed explanation, its really helpful <3

> But it seems that I accidentally forgot to add the `continue` at the end of this if statement.

Should I add one? It seems to be the intended behaviour anyways.

**Comment by timocov** [comment]
> Should I add one? It seems to be the intended behaviour anyways.

Yes, please. If you add it, it seems that you won't need to do anything else related to this particular issue (e.g. https://github.com/timocov/dts-bundle-generator/pull/183/files#diff-5554c0b3649d68de687551481713522cf40d31aa531ea9fb666d71a8ba7afe71R459-R462)

**Comment by timocov** [comment]
Hey @gamemaker1, what's about the test case from https://github.com/timocov/dts-bundle-generator/pull/183#issuecomment-1004264790 (about default export with a name)?

File: src/helpers/typescript.ts [hunk 4]
```diff
@@ -22,6 +22,19 @@ export function hasNodeModifier(node: ts.Node, modifier: ts.SyntaxKind): boolean
 	return Boolean(node.modifiers && node.modifiers.some((nodeModifier: ts.Modifier) => nodeModifier.kind === modifier));
 }
 
+export function getNodeName(node: ts.Node): ts.NamedDeclaration['name'] {
+	const nodeName = (node as unknown as ts.NamedDeclaration).name;
+	if (nodeName === undefined) {
+		const defaultModifier = node.modifiers?.find((mod: ts.Modifier) => mod.kind === ts.SyntaxKind.DefaultKeyword);
+		if (defaultModifier !== undefined) {
+			return defaultModifier as unknown as ts.DeclarationName;
```
Comment (timocov) [inline src/helpers/typescript.ts:30]: Hm, I don't think that it's safe to do this. I think we can change the returned type to `ts.NamedDeclaration['name'] | ts.DefaultKeyword` and use this type in `getDeclarationNameSymbol` and `getExportsForName`

File: src/bundle-generator.ts [hunk 5]
```diff
@@ -258,23 +259,25 @@ export function generateDtsBundle(entries: readonly EntryPointConfig[], options:
...
+					// an export keyword (like interface, type, etc) otherwise, if there are
+					// only re-exports with renaming (like export { foo as bar }) we don't need
+					// to put export keyword for this statement because we'll re-export it in the way
+					const hasNoDefaultExport = statementExports.find((exp: SourceFileExport) => exp.exportedName === 'default') === undefined;
+					// If true, the exported node has a name. If the node has no name (anonymous)
+					// function/class, then keep the `export default` keyword
+					const isNamedExport = getNodeName(statement) !== undefined;
+					const isPartOfRootSourceFile = rootSourceFile.fileName === statement.getSourceFile()?.fileName;
+
+					return hasNoDefaultExport || (isNamedExport && !isPartOfRootSourceFile);
```
Comment (timocov) [inline src/bundle-generator.ts:272]: 1. It seems that to check whether an exported with `default` node has a name or not you could check whether a found default export's original name is `default`: `defaultExport.originalName !== 'default'` where `defaultExport` is `statementExports.find((exp: SourceFileExport) => exp.exportedName === 'default')`
2. I think it would be better to change a check whether a node is from root source file by checking it's source file rather than it's filename: `statement.getSourceFile() !== rootSourceFile`

So it seems that these changes could like this:

```suggestion
					// a statement should have a 'default' keyword only if it it declared in the root source file
					// otherwise it will be re-exported via `export { name as default }`
					const defaultExport = statementExports.find((exp: SourceFileExport) => exp.exportedName === 'default');
					return defaultExport === undefined || defaultExport.originalName !== 'default' && statement.getSourceFile() !== rootSourceFile;
```

File: src/bundle-generator.ts [hunk 6]
```diff
@@ -435,20 +447,24 @@ function updateResultForRootSourceFile(params: UpdateParams, result: CollectingR
 	// add skipped by `updateResult` exports
 	for (const statement of params.statements) {
 		// "export default" or "export ="
-		const isExportAssignment = ts.isExportAssignment(statement);
-		const isReExportFromImportable = isReExportFromImportableModule(statement);
-
-		if (isExportAssignment || isReExportFromImportable) {
+		if (ts.isExportAssignment(statement) || isReExportFromImportableModule(statement)) {
```
Comment (timocov) [inline src/bundle-generator.ts:450]: would you mind to revert this changes? it seems that nothing was changed here

File: src/bundle-generator.ts [hunk 7]
```diff
@@ -435,20 +447,24 @@ function updateResultForRootSourceFile(params: UpdateParams, result: CollectingR
...
 		// export { foo, bar, baz as fooBar }
 		if (ts.isExportDeclaration(statement) && statement.exportClause !== undefined && ts.isNamedExports(statement.exportClause)) {
 			for (const exportItem of statement.exportClause.elements) {
+				// export { default }
 				if (exportItem.name.getText() === 'default' && exportItem.propertyName === undefined) {
-					// export { default }
-					// return export { /get name of exportItem.name's symbol node/ as default };
-					// it seems unnecessary?
+					// Leave `export { default } from 'external-package'` untouched
+					if (isDeclarationFromExternalModule(params.resolveIdentifier(exportItem.name)!.getSourceFile())) {
```
Comment (timocov) [inline src/bundle-generator.ts:462]: what this check is for? what did you want to check here?

File: src/bundle-generator.ts [hunk 8]
```diff
@@ -435,20 +447,24 @@ function updateResultForRootSourceFile(params: UpdateParams, result: CollectingR
...
+						continue;
+					}
+
+					const resolvedIdentifier = params.resolveIdentifier(exportItem.name);
+					result.renamedExports.push(`${resolvedIdentifier?.getText()} as default`);
```
Comment (timocov) [inline src/bundle-generator.ts:467]: what if node's name will be `undefined` so the result text will be `{ undefined as default }`? I think we need to add a test case for that, see the bottom section in this comment https://github.com/timocov/dts-bundle-generator/pull/183#issuecomment-1004264790

File: src/bundle-generator.ts [hunk 9]
```diff
@@ -295,7 +298,16 @@ export function generateDtsBundle(entries: readonly EntryPointConfig[], options:
...
+					// If the statement has *only* a named default export, then remove the
+					// `default` and `export` keywords. The node should be re-exported as
+					// default from the root source file instead.
+					const isOnlyExportedAsDefault = statementExports.length === 1 && statementExports.find((symbol) => symbol.exportedName === 'default') !== undefined;
+					const isNamedExport = getNodeName(statement) !== undefined;
+					const isPartOfRootSourceFile = rootSourceFile.fileName === statement.getSourceFile()?.fileName;
+
+					if (isOnlyExportedAsDefault && isNamedExport && !isPartOfRootSourceFile) {
+						result = false;
+					} else if (onlyDirectlyExportedShouldBeExported) {
```
Comment (timocov) [inline src/bundle-generator.ts:310]: it seems that it could be done easily. [in this code](https://github.com/timocov/dts-bundle-generator/blob/520b76ecc46cc1ab0e1468848cdc76b4fe4e297e/src/bundle-generator.ts#L280-L285) we check whether a node has any export which we should consider to treat as "truly-exported". So we can slightly modify so `shouldBeDefaultExportedDirectly` should be `true` only in case of `statement.getSourceFile() === rootSourceFile` and all this code could be reverted back.

**Review by timocov — CHANGES_REQUESTED** [review]

**Comment by timocov** [comment]
@gamemaker1 I left some comments to your changed. Also, could you fix lint issues as well? Thanks!

File: src/helpers/typescript.ts (hunk 4 above)
Comment (gamemaker1) [reply src/helpers/typescript.ts:30]: Done in `c64fdc2`!

Comment (gamemaker1) [reply src/helpers/typescript.ts]: Done in c64fdc2!

File: src/bundle-generator.ts (hunk 6 above)
Comment (gamemaker1) [reply src/bundle-generator.ts:450]: Oh sorry about that I think I did that when I was trying to address [this](https://github.com/timocov/dts-bundle-generator/pull/183#discussion_r778977677) :/

File: src/bundle-generator.ts (hunk 7 above)
Comment (gamemaker1) [reply src/bundle-generator.ts:462]: As the comment above it says: 'Leave `export { default } from 'external-package'` untouched'.

It addresses [this](https://github.com/timocov/dts-bundle-generator/pull/183/files/2b5e78669c778fe2d6455e3733e3e47af28f6da9#diff-ca21252d7fdfc2b40e9ef36b94f6c1381bdcb18b48f374cb5f1bfc53dd67ff7bR7) test case and [this](https://github.com/timocov/dts-bundle-generator/pull/183#issuecomment-1004266341) comment.

Comment (gamemaker1) [reply src/bundle-generator.ts:462]: It just checks if the string (here, 'external-package') is an external module or a file

File: src/bundle-generator.ts (hunk 8 above)
Comment (gamemaker1) [reply src/bundle-generator.ts:467]: Ooh I missed that test case, will add it now!

File: src/bundle-generator.ts (hunk 9 above)
Comment (gamemaker1) [reply src/bundle-generator.ts]: Done!

File: src/bundle-generator.ts (hunk 8 above)
Comment (gamemaker1) [reply src/bundle-generator.ts]: Done in c7aba43!

**Comment by gamemaker1** [comment]
Fixed the lint issues and also added second the test case from https://github.com/timocov/dts-bundle-generator/pull/183#issuecomment-1004264790!

File: src/helpers/typescript.ts [hunk 10]
```diff
@@ -22,6 +22,18 @@ export function hasNodeModifier(node: ts.Node, modifier: ts.SyntaxKind): boolean
 	return Boolean(node.modifiers && node.modifiers.some((nodeModifier: ts.Modifier) => nodeModifier.kind === modifier));
 }
 
+export function getNodeName(node: ts.Node): ts.NamedDeclaration['name'] | ts.Modifier {
```
Comment (timocov) [inline src/helpers/typescript.ts:25]:
```suggestion
export function getNodeName(node: ts.Node): ts.NamedDeclaration['name'] | ts.DefaultKeyword {
```

File: src/helpers/typescript.ts [hunk 11]
```diff
@@ -30,7 +42,7 @@ export function getActualSymbol(symbol: ts.Symbol, typeChecker: ts.TypeChecker):
 	return symbol;
 }
 
-export function getDeclarationNameSymbol(name: ts.DeclarationName, typeChecker: ts.TypeChecker): ts.Symbol | null {
+export function getDeclarationNameSymbol(name: ts.DeclarationName | ts.Modifier, typeChecker: ts.TypeChecker): ts.Symbol | null {
```
Comment (timocov) [inline src/helpers/typescript.ts:45]:
```suggestion
export function getDeclarationNameSymbol(name: ts.DeclarationName | ts.DefaultKeyword, typeChecker: ts.TypeChecker): ts.Symbol | null {
```

File: src/helpers/typescript.ts [hunk 12]
```diff
@@ -262,13 +274,13 @@ export function getExportsForStatement(
...
 
-	return getExportsForName(exportedSymbols, typeChecker, (statement as unknown as ts.NamedDeclaration).name);
+	return getExportsForName(exportedSymbols, typeChecker, getNodeName(statement));
 }
 
 function getExportsForName(
 	exportedSymbols: readonly SourceFileExport[],
 	typeChecker: ts.TypeChecker,
-	name: ts.NamedDeclaration['name']
+	name: ts.NamedDeclaration['name'] | ts.Modifier
```
Comment (timocov) [inline src/helpers/typescript.ts:283]:
```suggestion
	name: ts.NamedDeclaration['name'] | ts.DefaultKeyword
```

File: src/bundle-generator.ts [hunk 13]
```diff
@@ -440,22 +436,33 @@ function updateResultForRootSourceFile(params: UpdateParams, result: CollectingR
...
 					continue;
 				}
 
 				// export { default as name }
 				if (exportItem.propertyName !== undefined && exportItem.propertyName.getText() === 'default') {
-					const resolvedIdentifier = params.resolveIdentifier(exportItem.propertyName);
-					const resolvedIdentifierText = resolvedIdentifier?.getText() || '';
+					const resolvedIdentifier = params.resolveIdentifier(exportItem.name);
+					if (!resolvedIdentifier) {
+						continue;
```
Comment (timocov) [inline src/bundle-generator.ts:462]: could you please add a test case for that as well? it looks like a bug tbh

File: src/bundle-generator.ts [hunk 14]
```diff
@@ -440,22 +436,33 @@ function updateResultForRootSourceFile(params: UpdateParams, result: CollectingR
...
 		if (ts.isExportDeclaration(statement) && statement.exportClause !== undefined && ts.isNamedExports(statement.exportClause)) {
 			for (const exportItem of statement.exportClause.elements) {
+				// export { default }
 				if (exportItem.name.getText() === 'default' && exportItem.propertyName === undefined) {
-					// export { default }
-					// return export { /get name of exportItem.name's symbol node/ as default };
-					// it seems unnecessary?
+					// Leave `export { default } from 'external-package'` untouched
+					const exportedNode = params.resolveIdentifier(exportItem.name);
+					if (!exportedNode || isDeclarationFromExternalModule(exportedNode.getSourceFile())) {
```
Comment (timocov) [inline src/bundle-generator.ts:450]:
```suggestion
					const exportedNode = params.resolveIdentifier(exportItem.name);
					if (exportedNode === undefined) {
```

from my understanding

> Leave `export { default } from 'external-package'` untouched

this is already handled by added a `continue` keyword above. do you have a case when this condition works as well?

File: src/bundle-generator.ts [hunk 15]
```diff
@@ -440,22 +436,33 @@ function updateResultForRootSourceFile(params: UpdateParams, result: CollectingR
...
+					result.renamedExports.push(`${exportedNode.getText()} as default`);
 					continue;
 				}
 
 				// export { default as name }
 				if (exportItem.propertyName !== undefined && exportItem.propertyName.getText() === 'default') {
-					const resolvedIdentifier = params.resolveIdentifier(exportItem.propertyName);
-					const resolvedIdentifierText = resolvedIdentifier?.getText() || '';
+					const resolvedIdentifier = params.resolveIdentifier(exportItem.name);
+					if (!resolvedIdentifier) {
```
Comment (timocov) [inline src/bundle-generator.ts:461]:
```suggestion
					if (resolvedIdentifier === undefined) {
```

File: src/bundle-generator.ts [hunk 16]
```diff
@@ -467,13 +474,13 @@ function updateResultForRootSourceFile(params: UpdateParams, result: CollectingR
...
 
-				// export { baz as propertyName }
+				// export { name }
 				if (exportItem.propertyName !== undefined) {
 					result.renamedExports.push(exportItem.getText());
 					continue;
 				}
 
-				// export { name }
+				// export { baz as propertyName }
```
Comment (timocov) [inline src/bundle-generator.ts:483]: haha, good catch! 😄

**Review by timocov — CHANGES_REQUESTED** [review]

**Comment by timocov** [comment]
Oops, it seems that I broke that pipeline so I have to fix now.

File: src/bundle-generator.ts (hunk 13 above)
Comment (timocov) [reply src/bundle-generator.ts:462]: it seems that the case where the you're exporting unnamed default export without a name is not supported for now. I'll create a separate issue for this.

Comment (timocov) [reply src/bundle-generator.ts:462]: Here we go https://github.com/timocov/dts-bundle-generator/issues/185

**Review by timocov — APPROVED** [review]

**Comment by timocov** [comment]
Many thanks @gamemaker1 for all your hard work on this!

**Comment by gamemaker1** [comment]
Thanks for your help on this PR @timocov!

**Review by Githubrostro — APPROVED** [review]
